### ISSUE TITLE
Support Twig 1.x

### ISSUE THREAD

**Issue by patdunlavey** [lyrasis/islandora_aspace#22]
Currently only Twig 2.x is supported by this module, which in turn requires PHP 7. I have a client who wishes to test this module on a PHP 5 setup. 

I'll assign this task to myself and see if I can come up with a PR to fix this!

**Comment by bcah** [comment]
Hello Pat,

The Islandora Vagrant Box comes shipped with PHP 5.5.9, and we are using that box to serve an integrated ASpace/Islandora sandbox. We could benefit greatly by a solution to this issue.

Best,
Paul

**Comment by jonathangreen** [comment]
Should be resolved with: 
https://github.com/lyrasis/islandora_aspace/pull/23
